# Generated by Django 5.0.12 on 2025-02-08 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
